/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_cacodaemon_rpiws28114j_WS2811 */

#ifndef _Included_de_cacodaemon_rpiws28114j_WS2811
#define _Included_de_cacodaemon_rpiws28114j_WS2811
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_cacodaemon_rpiws28114j_WS2811
 * Method:    _addChannel
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_de_cacodaemon_rpiws28114j_WS2811__1addChannel
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

/*
 * Class:     de_cacodaemon_rpiws28114j_WS2811
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_cacodaemon_rpiws28114j_WS2811__1init
  (JNIEnv *, jclass);

/*
 * Class:     de_cacodaemon_rpiws28114j_WS2811
 * Method:    _setPixel
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_cacodaemon_rpiws28114j_WS2811__1setPixel
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     de_cacodaemon_rpiws28114j_WS2811
 * Method:    _render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_cacodaemon_rpiws28114j_WS2811__1render
  (JNIEnv *, jclass);

/*
 * Class:     de_cacodaemon_rpiws28114j_WS2811
 * Method:    _close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_cacodaemon_rpiws28114j_WS2811__1close
  (JNIEnv *, jclass);

/*
 * Class:     de_cacodaemon_rpiws28114j_WS2811
 * Method:    _getRpiPwmChannelCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_cacodaemon_rpiws28114j_WS2811__1getRpiPwmChannelCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
